version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: project_db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    # Uncomment the following lines for setting resource limits in production
    # mem_limit: 500m
    # cpu_shares: 10

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    expose:
      - 6379
    # mem_limit: 250m
    # cpu_shares: 10
    restart: on-failure

  worker:
    build: ./backend
    command: sh -c "celery -A pinboard.celery.app worker --loglevel=info"
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis
      - backend
    environment:
      DEBUG: 1
      SECRET_KEY: 1234567890
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: project_db
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    # mem_limit: 300m
    # cpu_shares: 10

  beat:
    build: ./backend
    restart: on-failure
    command: sh -c "celery -A pinboard.celery.app beat -l info"
    volumes:
      - ./backend:/code
    depends_on:
      - backend
      - redis
      - db
      - worker

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DEBUG: 1
      SECRET_KEY: 1234567890
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: project_db
      SQL_USER: postgres
      SQL_PASSWORD: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # mem_limit: 500m
    # cpu_shares: 10

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # mem_limit: 300m
    # cpu_shares: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: toygar.aksoy@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    # mem_limit: 300m
    # cpu_shares: 10

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - 5555:5555
    expose:
      - 5555
    depends_on:
      - redis
      - worker
    # mem_limit: 250m
    # cpu_shares: 10

volumes:
  postgres_data:
