# Generated by Django 5.0 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="created_at",
            new_name="created_date",
        ),
        migrations.AddField(
            model_name="post",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
